### ISSUE TITLE
Item Type Name Update

### ISSUE THREAD

**Issue by TshepoMokhere** [ArasLabs/kanban-like-task-management#1]
Hi,

I downloaded and installed the project and got an error when I tried to use the solution. However I picked up that the Names/Prefix of the Solution's Item Types i.e. "YMA" have been renames in the code but not on the Item Types. The Method to delete the relationship must also be edited to change the name of the Item Type accordingly.

**Comment by EliJDonahue** [comment]
Hi Tshepo,
I've updated the prefixes so they all match. Try pulling the latest changes and see if that resolves the error.

**Comment by TshepoMokhere** [comment]
Hi Eli,
Thank you. It's working as expected.

**Comment by EliJDonahue** [comment]
Awesome! I'll close out the issue. Thanks for your feedback, Tshepo.
