### ISSUE TITLE
Card move from one board to another

### ISSUE THREAD

**Issue by TshepoMokhere** [ArasLabs/kanban-like-task-management#2]
Hi guys,
What would be the most efficient way to move a card from one board to another. What we looking at is having a button that when a card is selected and the button is invoked the card will be moved to another board. When a card has gone trhough it's stages from one board, we want to move it to another card without creating a new one in the other board.
![cardmove2](https://cloud.githubusercontent.com/assets/23334281/20267673/7d642bea-aa84-11e6-8928-468e5bd113a4.PNG)
![cardmove1](https://cloud.githubusercontent.com/assets/23334281/20267674/7e118ede-aa84-11e6-8575-76c816fc5f3f.PNG)

**Comment by EliJDonahue** [comment]
@YoannArasLab - Thoughts?

**Comment by YMA-MDL** [comment]
Hi Sorry for the delay, I'm not sure why I didn't get the notification.

> What we looking at is having a button that when a card is selected and the button is invoked the card will be moved to another board. 
For this we would add a button on the card, and opening a popup window showing the available projects. Shouldn't be much work. @TshepoMokhere can you do it?

> When a card has gone trhough it's stages from one board, we want to move it to another card without creating a new one in the other board
Not sure I understand this requirement? Is there a wording error ?

**Comment by YoannArasLab** [comment]
Hi Sorry for the delay, I'm not sure why I didn't get the notification.

> What we looking at is having a button that when a card is selected and the button is invoked the card will be moved to another board. 

For this we would add a button on the card, and opening a popup window showing the available projects. Shouldn't be much work. @TshepoMokhere can you do it?

> When a card has gone trhough it's stages from one board, we want to move it to another card without creating a new one in the other board

Not sure I understand this requirement? Is there a wording error ?

**Comment by TshepoMokhere** [comment]
Hi Yoann,
The second statement was an elaboration on the first however it does have  some errors, however it's answered by your first response.

We've got the functionality working however my only interest is whether there is an easier way to get it than how we did it. I will upload screenshots of what we did and it's behaviour.

**Comment by TshepoMokhere** [comment]
The next thing we are looking at is a query that we want to happen. The Card will have related projects and when certain project tasked have not been completed the user is unable to drag the card to the next stage.
![cardselection](https://cloud.githubusercontent.com/assets/23334281/20827772/beca8ae2-b87c-11e6-8f4c-84baa16fe156.png)
![code1](https://cloud.githubusercontent.com/assets/23334281/20827773/becdba6e-b87c-11e6-8065-f71a008e8696.png)
![code2](https://cloud.githubusercontent.com/assets/23334281/20827775/bed0bed0-b87c-11e6-8922-4fc2e18d7c83.png)
![destinationboardselection](https://cloud.githubusercontent.com/assets/23334281/20827774/bece673e-b87c-11e6-85a7-59a77c5af3b4.png)



`

**Comment by YoannArasLab** [comment]
Nice job for the card transfer !
Not sure if you are familiar with Jquery, and it is more than fine to do most of the coding pure javascript, but jquery is loaded with the board page so you can benefit from it like:
```
$(".spanAccept").click(function(){
});
```
For getting the project information, you need to get the project itemproperty from the card and then have a query for the project. Let me know if you have trouble getting your project structure. You can still find some good info on the AML studio codeplex page : https://amlstudio.codeplex.com/documentation (they moved now to github for the latest Innovator admin tool)

**Comment by TshepoMokhere** [comment]
Thanks Yoann,
I'll have a look at it.
