### ISSUE TITLE
Project Innovator/Boards, No graphic interface 

### ISSUE THREAD

**Issue by seb155** [ArasLabs/kanban-like-task-management#5]
In the TOC, I select Project Innovator/Boards,

But in the main windows there is no graphic interface with "cards".
There is only a table, with Boards properties ( Statuses, name, description, wallpaper, wallpaperURL, creatorPicture.

Package installation was successful and files copied to innovator directory.
I'm using Aras innovator 11SP9,

**Comment by YoannArasLab** [comment]
If the Package installation was successful then maybe the files location is not correct.
Can you check two things:

1. check that in the Itemtype Lab_Boards, in tab "TOC View" you have the reference to the html page you should have copied

2. Please then check if the path to this file is correct. the root folder ( . ) is the scripts folder in your innovator install. (Innovator/client/scripts)

Hope this helps

**Comment by seb155** [comment]
Thanks it's working .
